export const defaultTheme = {
  colorWhite: "#FFFFFF",
  colorBlackForText: "#333333",
  colorForButton: "#FC9B27",
  backgroundColorGray: "#f7f7f7",
  colorForButtonHover: "#FC7427",
  colorForLightBackground: "#D8ECFE",
  colorForDarkBackground: "#C4E2FF",
  colorForBackgrundFeature: "#E1EDCE",
  colorForBackgrundFeatureNegative: "#F8DDD7",
  colorForBackgrundFeatureOwner: "#88AA4D",
  colorForBackgrundFeatureOwnerNegative: "#F75531",
  pagePadding: "90px",
  padding: "20px",
  indent: "64px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  lineHeightDefault: "27px",
  minHeight: "80px",
  pageWidth: "1280px",
  headerHeight: "80px",
  footerHeight: "80px",
};
